version: '2'

services:
  webapp:
    image: webapp
    build:
      context: ./WebApp
      dockerfile: Dockerfile
    ports:
      - "8888:80"
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "8889:4444"
    links:
      - webapp